version: "2.4"

services:
  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/arnaudlacour/sybase-sync.git
      - SERVER_PROFILE_PATH=pingdirectory
      - USER_BASE_DN=o=data
      - MAX_HEAP_SIZE=768m
    env_file:
      - ${HOME}/.pingidentity/devops
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: 1g
    memswap_limit: 1g
    oom_kill_disable: true
    mem_swappiness: 0
    tmpfs: /run/secrets
    ports:
      - "1636:1636"
      - "1443:1443"
    networks:
      - pingnet
    volumes:
      - pingdirectory-out:/opt/out

  pingdatasync:
    image: pingidentity/pingdatasync:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/arnaudlacour/sybase-sync.git
      - SERVER_PROFILE_PATH=pingdatasync
      - USER_BASE_DN=o=data
      - MAX_HEAP_SIZE=384m
    env_file:
      - ${HOME}/.pingidentity/devops
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    mem_limit: 512m
    memswap_limit: 512m
    oom_kill_disable: true
    mem_swappiness: 0
    tmpfs: /run/secrets    
    ports:
      - "2636:1636"
      - "2443:1443"
    networks:
      - pingnet
    volumes:
      - pingdatasync-out:/opt/out

  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - "8443:8443"
    networks:
      - pingnet

  sybase:
    image: datgrip/sybase:16.0
    ports:
      - "5000:5000"
    networks:
      - pingnet

networks:
  pingnet:

volumes:
  pingdirectory-out:
  pingdatasync-out:
